### ISSUE TITLE
Working issue

### ISSUE THREAD

**Issue by ikoliHU** [mikeyaworski/Auto-Claim-Twitch-Channel-Points#2]
Sadly this is not working anymore

**Comment by mikeyaworski** [comment]
I see the reason. Will fix it ASAP.

**Comment by mikeyaworski** [comment]
Published a new version which should fix this (1.0.7).

Go ahead and update your extension, and let me know if you still run into the issue.

**Comment by ikoliHU** [comment]
Sadly still not working

**Comment by mikeyaworski** [comment]
Since the mutation observer logic is bug prone, I added an option to the extension which lets you choose either
- `Interval`, or
- `Mutation Observer`

One of those should work for you. Let me know what happens.

The new published version is `1.0.8`.
